### ISSUE TITLE
Opens, but doesn't close the UV Editor in Blender 3.0.0 Alpha

### ISSUE THREAD

**Issue by LarsJandel** [DotBow/Blender-Sticky-UV-Editor-Add-on#1]
Very handy add-on - thanks for scripting it!

Sorry to bother you with a Blender Alpha version related issue, but maybe it is an easy fix..?
Opening the UV Editor works as expected, but unfortunately, it won't close it again.
Only the Toolbar in the 3D view flashes instead.

Thanks

**Comment by DotBow** [comment]
Hi! Sorry for late answer!
I checked the issue and it seems that it might be an internal Blender bug...

**Comment by LarsJandel** [comment]
No worries and thanks for looking into it.
Regarding some other add-ons, it just happens that I have to use 2.93 anways for the current project. 😅👍
Maybe the Blender issue will be fixed in the future. 🤷‍♂️

Thanks!

**Comment by DotBow** [comment]
> 
> 
> No worries and thanks for looking into it.
> Regarding some other add-ons, it just happens that I have to use 2.93 anways for the current project. 😅👍
> Maybe the Blender issue will be fixed in the future. 🤷‍♂️
> 
> Thanks!

I finally take a time to report a bug, it is confirmed and Harley is up to it!

https://developer.blender.org/T90731

**Comment by DotBow** [comment]
Support for 3.0.0 added in https://github.com/DotBow/Blender-Sticky-UV-Editor-Add-on/releases/tag/v1.1.0

**Comment by LarsJandel** [comment]
Thanks! 🙏
