### ISSUE TITLE
Error on activating plugin with Shift+T

### ISSUE THREAD

**Issue by Victor767** [DotBow/Blender-Sticky-UV-Editor-Add-on#3]
Hi! I like your add-on so much! It works perfectly well on Blender 3.2 but does not work as expected on Blender 2.93.9. When I press Shift+T combination it opens UV Editor window on the left side but also shows the error:

```
Python: Traceback (most recent call last):
  File "C:\Users\ViC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sticky_uv_editor\__init__.py", line 351, in invoke
    uv_editor_settings.set(uv_area)
  File "C:\Users\ViC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sticky_uv_editor\uv_editor_settings.py", line 116, in set
    uv_editor.use_custom_grid = self.use_custom_grid
AttributeError: 'SpaceUVEditor' object has no attribute 'use_custom_grid'

location: <unknown location>:-1
```

When I try to close the UV Editor window with Shift+T it doesn't do that and the same error appears instead.

I tried to delete the whole profile folder

`C:\Users\ViC\AppData\Roaming\Blender Foundation\Blender\2.93`

and install your add-on but got no success - the same error and the window stays where it was. So it seems this add-on has no issues with 3.2 version but has the issue with LTS branch of the Blender meaning 2.93.9 version.

Just can't live without it so would be grateful for your attention to this issue and some fix to it for 2.93 version :)

Thank you in advance.

**Comment by DotBow** [comment]
Hi! Thanks for report!

Should be fixed in [1.3.0](https://github.com/DotBow/Blender-Sticky-UV-Editor-Add-on/releases/tag/v1.3.0)
